<?php
/**
 * Triangular, pentagonal, and hexagonal
 * Problem 45
 *
 * Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
 * Triangle 	Tn=n(n+1)/2 	1, 3, 6, 10, 15, ...
 * Pentagonal 	Pn=n(3n−1)/2 	1, 5, 12, 22, 35, ...
 * Hexagonal 	Hn=n(2n−1) 	  	1, 6, 15, 28, 45, ...
 *
 * It can be verified that T285 = P165 = H143 = 40755.
 *
 * Find the next triangle number that is also pentagonal and hexagonal.
 *
 * Answer: 1533776805
 */

$log = new \Util\Log();
$tri = new \Sequence\TriangleNumber();
$pen = new \Sequence\Pentagonal();
$hex = new \Sequence\Hexagonal();

$found = array();
while ($n = $hex->next())
{
    if (! $pen->isPentagonal($n))
        continue;
    if (! $tri->isTriangleNumber($n))
        continue;
    $found[] = $n;
    if ($n > 40755)
        break;
}

print_r($found);

$log->solution(max($found));